rcamp/accounts/urls.py
from django.urls import include, path, re_path
from . import admin
from accounts.views import (
    AccountRequestOrgSelectView,
    AccountRequestVerifyUcbView,
    AccountRequestVerifyCsuView,
    AccountRequestIntentView,
    AccountRequestReviewView,
)


urlpatterns = [
    re_path(
        r'^account-request/create/organization$',
        AccountRequestOrgSelectView.as_view(),
        name='account-request-org-select'
    ),
    re_path(
        r'^account-request/create/verify/ucb$',
        AccountRequestVerifyUcbView.as_view(),
        name='account-request-verify-ucb'
    ),
    re_path(
        r'^account-request/create/verify/csu$',
        AccountRequestVerifyCsuView.as_view(),
        name='account-request-verify-csu'
    ),
    re_path(
        r'^account-request/create/intent$',
        AccountRequestIntentView.as_view(),
        name='account-request-intent'
    ),
    re_path(
        r'^account-request/review$',
        AccountRequestReviewView.as_view(),
        name='account-request-review'
    ),
]

# removed path('admin/accounts/comanageuser/<int:user_id>/sync/', sync_user_from_comanage, name='accounts_comanageuser_sync'),

rcamp/rcamp/urls.py
from django.urls import include, re_path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.conf.urls import handler404
from django.conf.urls import handler500
from django.conf import settings
# Make sure signals/receivers get loaded.
from mailer import receivers
from projects import receivers
from lib.views import index_view



handler404 = 'lib.views.handler404'
handler500 = 'lib.views.handler500'

urlpatterns = [
    re_path(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    re_path(r'^$', index_view, name='index'),
    re_path(r'^login', auth_views.LoginView.as_view(template_name='registration/login.html')),
    re_path(r'^logout', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^api/', include('endpoints.urls')),
    re_path(r'^accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    re_path(r'^projects/', include(('projects.urls', 'projects'), namespace='projects')),
]


if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += staticfiles_urlpatterns()

rcamp/accounts/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.views.decorators.debug import sensitive_variables
from django.contrib.auth.models import AbstractUser
from lib import ldap_utils
#from lib.utils import get_user_and_groups, get_comanage_users_by_org, sync_group_to_comanage, get_group_id
import ldapdb.models.fields as ldap_fields
import ldapdb.models
import logging
import datetime
import pam

from mailer.signals import (
    account_created_from_request,
    account_request_approved
)

# Create your models here.
ORGANIZATIONS = tuple([(k,v['long_name']) for k,v in settings.ORGANIZATION_INFO.items()])

REQUEST_ROLES = (
    ('undergraduate','Undergraduate',),
    ('graduate','Graduate',),
    ('postdoc','Post Doc',),
    ('instructor','Instructor',),
    ('faculty','Faculty',),
    ('affiliated_faculty','Affiliated Faculty',),
    ('staff','Staff',),
    ('sponsored','Sponsored Affiliate',),
)

NSF_DISCIPLINES = (
    ('Computer & Information Services', 'Computer & Information Services'),
    ('Engineering', 'Engineering'),
    ('Geosciences, Atmospheric Sciences & Ocean Sciences', 'Geosciences, Atmospheric Sciences & Ocean Sciences'),
    ('Life Sciences', 'Life Sciences'),
    ('Mathematics and Statistics', 'Mathematics and Statistics'),
    ('Physical Sciences', 'Physical Sciences'),
    ('Psychology', 'Psychology'),
    ('Social Sciences', 'Social Sciences'),
    ('Other Sciences (not elsewhere classified)', 'Other Sciences (not elsewhere classified)'),
    ('Education', 'Education'),
    ('Law', 'Law'),
    ('Humanities', 'Humanities'),
    ('Visual & Performing Arts', 'Visual & Performing Arts'),
    ('Business Management and Business Administration', 'Business Management and Business Administration'),
    ('Communications, Communications Technologies, Journalism (Library Science is considered “Other Non-Science & Engineering Fields”)', 'Communications, Communications Technologies, Journalism (Library Science is considered “Other Non-Science & Engineering Fields”)'),
    ('Social Work', 'Social Work'),
    ('Other Non-Science & Engineering Fields', 'Other Non-Science & Engineering Fields'),
)

ROLES = REQUEST_ROLES + (
    ('pi','Principal Investigator',),
    ('admin','Admin',),
)

SHELL_CHOICES = (
    ('/bin/bash','bash'),
    ('/bin/tcsh','tcsh'),
)

class User(AbstractUser):
    @property
    def organization(self):
        _, organization = ldap_utils.get_ldap_username_and_org(self.username)
        return organization

    @property
    def ldap_username(self):
        ldap_username, _ = ldap_utils.get_ldap_username_and_org(self.username)
        return ldap_username

    def get_ldap_user(self):
        """Return the RcLdapUser associated with this account."""
        ldap_user = RcLdapUser.objects.get_user_from_suffixed_username(self.username)
        return ldap_user


class AccountRequest(models.Model):
    class Meta:
        unique_together = (('username','organization'),)

    STATUSES = (
        ('p','Pending'),
        ('a','Approved'),
        ('d','Denied'),
        ('i','Incomplete'),
    )

    username = models.CharField(max_length=48)
    first_name = models.CharField(max_length=128,blank=False,null=False)
    last_name = models.CharField(max_length=128,blank=False,null=False)
    email = models.EmailField(unique=True)

    organization = models.CharField(max_length=128,choices=ORGANIZATIONS,blank=False,null=False)
    department = models.CharField(max_length=128,blank=True,null=True)
    role = models.CharField(max_length=24,choices=REQUEST_ROLES,default='undergraduate')
    discipline = models.CharField(max_length=256,choices=NSF_DISCIPLINES,blank=True, null=True)
    status = models.CharField(max_length=16,choices=STATUSES,default='p')
    approved_on = models.DateTimeField(null=True,blank=True)
    notes = models.TextField(null=True,blank=True)
    id_verified_by = models.CharField(max_length=128,blank=True,null=True)
    request_date = models.DateTimeField(auto_now_add=True)

    # TODO: Deprecate these fields, as they are now represented in the Intent object
    login_shell = models.CharField(max_length=24,choices=SHELL_CHOICES,default='/bin/bash')
    resources_requested = models.CharField(max_length=256,blank=True,null=True)
    sponsor_email = models.EmailField(blank=True,null=True)
    course_number = models.CharField(max_length=128,blank=True,null=True)

    def __str__(self):
        return '%s_%s'%(self.username,self.request_date)

    def save(self,*args,**kwargs):
        # Has model already been approved?
        manually_approved = False
        if (self.status == 'a') and (not self.approved_on):
            manually_approved = self.pk is not None
            # Approval process
            logger = logging.getLogger('accounts')
            logger.info('Approving account request: {}'.format(self.username))
            self.approved_on=timezone.now()
            rc_user = RcLdapUser.objects.create_user_from_request(
                username=self.username,
                first_name=self.first_name,
                last_name=self.last_name,
                email=self.email,
                organization=self.organization,
                role=self.role,
                discipline=self.discipline,
            )
            # Create associated auth user
            auth_user_defaults = dict(
                email=rc_user.email,
                first_name=rc_user.first_name,
                last_name=rc_user.last_name
            )
            auth_user, created = User.objects.update_or_create(
                username=rc_user.effective_uid,
                defaults=auth_user_defaults
            )
            # account_created_from_request.send(sender=rc_user.__class__,account=rc_user)

        if (self.status != 'a'):
            self.approved_on = None

        super(AccountRequest,self).save(*args,**kwargs)
        if manually_approved:
            logger = logging.getLogger('accounts')
            logger.info('Sending account_request_approved signal')
            account_request_approved.send(sender=self.__class__, account_request=self)
            logger.info('Signal sent: account_request_approved')
            
    def clean(self):
        # Custom validation to make discipline required if organization is 'xsede'
        if not self.discipline:
            raise ValidationError({'discipline': 'This field is required.'})
        super(AccountRequest, self).clean()

class Intent(models.Model):
    account_request = models.OneToOneField(
            AccountRequest,
            blank=True,
            null=True,
            on_delete=models.CASCADE
            )
    reason_summit = models.BooleanField(default=False)
    reason_course = models.BooleanField(default=False)
    reason_petalibrary = models.BooleanField(default=False)
    reason_blanca = models.BooleanField(default=False)
    sponsor_email = models.EmailField(blank=True,null=True)
    course_instructor_email = models.EmailField(blank=True,null=True)
    course_number = models.CharField(max_length=128,blank=True,null=True)
    summit_description = models.TextField(null=True,blank=True)
    summit_funding = models.TextField(null=True,blank=True)
    summit_pi_email = models.EmailField(blank=True,null=True)

class IdTracker(models.Model):
    class Meta:
        verbose_name = 'ID tracker'
        verbose_name_plural = 'ID trackers'

    category = models.CharField(max_length=12,blank=False,null=False,unique=True)
    min_id = models.IntegerField(blank=False,null=False)
    max_id = models.IntegerField(blank=False,null=False)
    next_id = models.IntegerField(blank=True,null=True)

    def __str__(self):
        return self.category

    def get_next_id(self):
        if self.next_id:
            uid = self.next_id
        else:
            uid = self.min_id
        while uid < self.max_id:
            rc_users = RcLdapUser.objects.filter(uid=uid)
            rc_groups = RcLdapGroup.objects.filter(gid=uid)

            if all([(len(rc_users)==0),(len(rc_groups)==0)]):
                self.next_id = uid + 1
                self.save()
                return uid
            else:
                uid += 1

class LdapUser(ldapdb.models.Model):
    class Meta:
        managed = False
        abstract=True

    rdn_keys = ['username']

    # inetOrgPerson
    first_name = ldap_fields.CharField(db_column='givenName')
    last_name = ldap_fields.CharField(db_column='sn')
    full_name = ldap_fields.CharField(db_column='cn')
    email = ldap_fields.CharField(db_column='mail')
    # posixAccount
    username = ldap_fields.CharField(db_column='uid')
    # ldap specific
    modified_date = ldap_fields.DateTimeField(db_column='modifytimestamp',blank=True)

    def __str__(self):
        return self.username

    def __str__(self):
        return self.full_name

    def save(self,*args,**kwargs):
        force_insert = kwargs.pop('force_insert',None)
        super(LdapUser,self).save(*args,**kwargs)

class RcLdapUserManager(models.Manager):
    def get_user_from_suffixed_username(self,suffixed_username):
        username, organization = ldap_utils.get_ldap_username_and_org(suffixed_username)
        users = [u for u in self.get_queryset().filter(username=username) if u.organization == organization]
        user = None
        if len(users) > 0:
            user = users[0]
        return user

    def create(self,*args,**kwargs):
        org = kwargs.pop('organization', None)
        obj = self.model(**kwargs)
        self._for_write = True
        obj.save(force_insert=True,using=self.db,organization=org)
        return obj

    def create_user_from_request(self,**kwargs):
        username = kwargs.get('username')
        if username is not None:
            username = str(username).strip()
            username = username.lower()
        first_name = kwargs.get('first_name')
        last_name = kwargs.get('last_name')

rcamp/accounts/forms.py
import logging

from django import forms
from django.contrib.admin.widgets import FilteredSelectMultiple
from django.views.decorators.debug import sensitive_variables
from lib.ldap_utils import get_suffixed_username
from accounts.models import (
    CuLdapUser,
    CsuLdapUser,
    RcLdapUser,
    AccountRequest,
    REQUEST_ROLES,
    NSF_DISCIPLINES
)


class AccountRequestVerifyForm(forms.Form):
    """
    An abstract form for verifying user credentials against a configured authority
    LDAP. Subclasses should set auth_user_model and organization attributes.

    For verification against CU for instance, AccountRequestVerifyForm.organization should be 'ucb'
    and the AccountRequestVerifyForm.auth_user_model should be CuLdapUser.
    """
    username = forms.CharField(max_length=48,required=True)
    password = forms.CharField(max_length=255,widget=forms.PasswordInput,required=True)
    department = forms.CharField(max_length=128,required=True)
    role = forms.ChoiceField(choices=REQUEST_ROLES,required=True)
    discipline = forms.ChoiceField(choices=NSF_DISCIPLINES, required=True)

    @sensitive_variables('password')
    def clean(self):
        cleaned_data = super(AccountRequestVerifyForm,self).clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        account_requests = AccountRequest.objects.filter(username=username,organization=self.organization)
        if account_requests.count() > 0:
            raise forms.ValidationError(
                'An account request has already been submitted for {}'.format(username)
            )
        try:
            suffixed_username = get_suffixed_username(username,self.organization)
            rc_user = RcLdapUser.objects.get_user_from_suffixed_username(suffixed_username)
            if rc_user:
                raise forms.ValidationError(
                    'An account already exists with username {}'.format(username)
                )

            authed = False
            auth_user = self.auth_user_model.objects.get(username=username)
            authed = auth_user.authenticate(password)
            if not authed:
                raise forms.ValidationError('Invalid password')
            return cleaned_data

        except UnboundLocalError:
            raise forms.ValidationError('Invalid organization')
        except self.auth_user_model.DoesNotExist:
            raise forms.ValidationError('Invalid username')
        except TypeError as e:
            logger = logging.getLogger('admin')
            logger.info("Type error")
            logger.exception(e, exc_info=True)
            raise forms.ValidationError('Missing field(s)')


class AccountRequestVerifyUcbForm(AccountRequestVerifyForm):
    organization = 'ucb'
    auth_user_model = CuLdapUser


class AccountRequestVerifyCsuForm(AccountRequestVerifyForm):
    organization = 'csu'
    auth_user_model = CsuLdapUser


class AccountRequestIntentForm(forms.Form):
    reason_summit = forms.BooleanField(required=False)
    reason_course = forms.BooleanField(required=False)
    reason_petalibrary = forms.BooleanField(required=False)
    reason_blanca = forms.BooleanField(required=False)

    # Alpine additional info
    summit_pi_email = forms.EmailField(required=False)
    summit_funding = forms.CharField(widget=forms.Textarea,required=False)
    summit_description = forms.CharField(widget=forms.Textarea,required=False)

    # Course follow-up
    course_instructor_email = forms.EmailField(required=False)
    course_number = forms.CharField(max_length=48,required=False)

rcamp/accounts/templates/account-request-create.html
{% extends "base.html" %}

{% block title %}Research Computing - Request Account{% endblock %}

{% block extra_style %}
<link href="/static/css/account-request.css" rel="stylesheet"/>
{% endblock %}

{% block jumbotron_heading %}<h1>Account Request</h1>{% endblock %}
{% block jumbotron_subheading %}
<p>Request an account with University of Colorado Boulder Research Computing.</p>
{% endblock %}
{% block jumbotron_button %}
<p><a data-toggle="modal" href="#helpmodal"
class="btn btn-primary btn-lg" role="button">Definitions &amp; Form Help &raquo;</a></p>
{% endblock %}

{% block modal_title %}
<h4 class="modal-title">Definitions &amp; Form Help</h4>
{% endblock %}
{% block modal_body %}
<ul class="list-group">
    <li class="list-group-item">
        <strong>Organization Credentials</strong>
        <p>The request form requires that you successfully authenticate against
          the organization with which you are affiliated to verify your identity.
          The organization credentials should be the username/password pair you
          to access your organization's resources.
        </p>
    </li>
</ul>
{% endblock %}

{% block container %}
<div class="mailto-help">
    Questions about the account request process?
    <a href="mailto:rc-help@colorado.edu?subject=Question%20About%20Account%20Request%20Process">
        Contact us
    </a>
    or view our
    <a href="https://www.rc.colorado.edu/support/getting-started.html">
      Getting Started Guide.
    </a>
</div>

{% if form.errors %}
<div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <p>
      <strong>Could not submit request.</strong>
      Please resolve the errors below, or
      <a href="mailto:rc-help@colorado.edu?subject=Question%20About%20Account%20Request%20Process">
          contact us.
      </a>
    </p>
    {{ form.non_field_errors }}
</div>
{% endif %}

<form class="form-horizontal" method="POST" action="" role="form" enctype="multipart/form-data">
    {% csrf_token %}

    <fieldset>
        <legend>Select your organization</legend>
        {% if form.organization.errors %}
        <div class="form-group has-error has-feedback">
        {% else %}
        <div class="form-group">
        {% endif %}
            <label class="col-sm-2 control-label" for="id_organization">Organization</label>
            <div class="col-sm-8">
                <select name="organization" id="id_organization" class="form-control">
                    {% for value, disp in form.organization.field.choices %}
                    <option value="{{ value }}">{{ disp }}</option>
                    {% endfor %}
                </select>
                {% if form.organization.errors %}
                <div class="alert alert-danger alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <strong>{{ form.organization.errors }}</strong>
                </div>
                {% endif %}
            </div>
        </div>
    </fieldset>

    <fieldset>
        <legend>Login With Organization Credentials</legend>
        {% if form.username.errors %}
        <div class="form-group has-error has-feedback">
        {% else %}
        <div class="form-group">
        {% endif %}
            <div class="col-sm-12">
              <p id="ucb-login-help"><i class="fa fa-info-circle" aria-hidden="true"></i> UCB users use their CU IdentiKey username and password.</p>
              <p id="csu-login-help"><i class="fa fa-info-circle" aria-hidden="true"></i> CSU users use their CSU EID as username. Password is <code>csu_password,duo_key</code> or <code>csu_password,push</code>.</p>
            </div>
            <label class="col-sm-2 control-label" for="id_username">Username</label>
            <div class="col-sm-8">
                <input id="id_username" type="text" name="username" class="form-control"
                {% if form.username.value %}value="{{ form.username.value }}"{% endif %}
                maxlength="256" />
                {% if form.username.errors %}
                <div class="alert alert-danger alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <strong>{{ form.username.errors }}</strong>
                </div>
                {% endif %}
            </div>
        </div>

        {% if form.password.errors %}
        <div class="form-group has-error has-feedback">
        {% else %}
        <div class="form-group">
        {% endif %}
            <label class="col-sm-2 control-label" for="id_password">Password</label>
            <div class="col-sm-8">
                <input id="id_password" type="password" name="password" class="form-control"
                {% if form.password.value %}value="{{ form.password.value }}"{% endif %}
                maxlength="256" />
                {% if form.password.errors %}
                <div class="alert alert-danger alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <strong>{{ form.password.errors }}</strong>
                </div>
                {% endif %}
            </div>
        </div>
    </fieldset>

    <fieldset>
        <legend>What is your role?</legend>
        {% if form.role.errors %}
        <div class="form-group has-error has-feedback">
        {% else %}
        <div class="form-group">
        {% endif %}
            <label class="col-sm-2 control-label" for="id_role">Role</label>
            <div class="col-sm-8">
                <select name="role" id="id_role" class="form-control">
                    {% for value, disp in form.role.field.choices %}
                    <option value="{{ value }}">{{ disp }}</option>
                    {% endfor %}
                </select>
                {% if form.role.errors %}
                <div class="alert alert-danger alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <strong>{{ form.role.errors }}</strong>
                </div>
                {% endif %}
            </div>
        </div>
    </fieldset>

    <fieldset>
        <legend>What is your preferred login shell?</legend>
        {% if form.login_shell.errors %}
        <div class="form-group has-error has-feedback">
        {% else %}
        <div class="form-group">
        {% endif %}
            <label class="col-sm-2 control-label" for="id_login_shell">Preferred login shell</label>
            <div class="col-sm-8">
                <select name="login_shell" id="id_login_shell" class="form-control">
                    {% for value, disp in form.login_shell.field.choices %}
                    <option value="{{ value }}">{{ disp }}</option>
                    {% endfor %}
                </select>
                {% if form.login_shell.errors %}
                <div class="alert alert-danger alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <strong>{{ form.login_shell.errors }}</strong>
                </div>
                {% endif %}
            </div>
        </div>
    </fieldset>

    <fieldset>
      <legend>Which resources do you intend to use?</legend>

      {% include "account-request-resource-checkboxes.html" %}
    </fieldset>

    <div class="col-sm-2 col-sm-offset-5 request-submit">
        <button type="submit" class="btn btn-primary btn-lg">Submit Request</button>
    </div>
</form>
{% endblock %}

rcamp/accounts/templates/account-request-org-select.html
{% extends "base.html" %}

{% block title %}Research Computing - Request Account{% endblock %}

{% block extra_style %}
<link href="/static/css/account-request.css" rel="stylesheet"/>
{% endblock %}

{% block container %}
<div class="row">
  <div class="jumbotron text-center">
    <h1>Account Request</h1>
    <p>Request a Research Computing account.</p>
  </div>
</div>

<legend>Please select your organization to begin.</legend>
<div class="alert alert-info" role="alert">
    If you're an RMACC user and do not see your organization listed, please follow the documentation on the RMACC tab of <a href="https://curc.readthedocs.io/en/latest/getting_started/logging-in.html">this page <span class="glyphicon glyphicon-new-window"></span></a>.
</div>

<div class="list-group">
  <a href="{% url 'accounts:account-request-verify-ucb' %}" class="list-group-item">
    <h4 class="list-group-item-heading">University of Colorado Boulder</h4>
    <p class="list-group-item-text">
      You will be asked to verify your identity with your CU IdentiKey username and password.
    </p>
  </a>
  <a href="{% url 'accounts:account-request-verify-csu' %}" class="list-group-item">
    <h4 class="list-group-item-heading">Colorado State University</h4>
    <p class="list-group-item-text">
      You will be asked to verify your identity with your CSU EID username and password.
    </p>
  </a>
</div>
{% endblock %}

rcamp/accounts/templates/account-request-review.html
{% extends "base.html" %}

{% block title %}Research Computing - Request Submitted{% endblock %}

{% block extra_style %}
<link href="/static/css/org-select.css" rel="stylesheet"/>
{% endblock %}

{% block container %}
<div class="row">
    <div class="jumbotron text-center">
        <h1>Account Request Submitted</h1>
        {% if account_request.status != 'a' %}
        <p>We will review your request within 7 days.</p>
        {% else %}
        <p>Welcome to Research Computing!</p>
        {% endif %}
    </div>
</div>

<div class="mailto-help">
    Questions about your request?
    <a href="mailto:rc-help@colorado.edu?subject=Question%20About%20Submitted%20Request%20(%23{{account_request.id}})">
        Contact us.
    </a>
</div>

<h2 class="sub-header">Request Details</h2>
    <div class="alert alert-success" role="alert">
      {% if account_request.status != 'a' %}
      We will contact you at <strong>{{ account_request.email }}</strong> with updates regarding your account request.
      {% else %}
      We have sent a confirmation to <strong>{{ account_request.email }}</strong>.
      {% endif %}
    </div>
    <div class="table-responsive">
        <table id="allocation-request-table" class="table table-striped">
            <tr>
                <td><strong>Request received on</strong></td>
                <td>{{account_request.request_date}}</td>
            </tr>
            <tr>
                <td><strong>Username</strong></td>
                <td>{{account_request.username}}</td>
            </tr>
            <tr>
                <td><strong>First name</strong></td>
                <td>{{account_request.first_name}}</td>
            </tr>
            <tr>
                <td><strong>Last name</strong></td>
                <td>{{account_request.last_name}}</td>
            </tr>
            <tr>
                <td><strong>Email address</strong></td>
                <td>{{account_request.email}}</td>
            </tr>
            <tr>
                <td><strong>Department</strong></td>
                <td>{{account_request.department}}</td>
            </tr>
            <tr>
                <td><strong>Role</strong></td>
                <td>{{account_request.get_role_display}}</td>
            </tr>
            <tr>
                <td><strong>Organization</strong></td>
                <td>{{ account_request.get_organization_display }}</td>
            </tr>
            <tr>
                <td><strong>Discipline</strong></td>
                <td>{{ account_request.get_discipline_display }}</td>
            </tr>
        </table>
    </div>
{% endblock %}

rcamp/accounts/templates/change_list.html
{% extends "admin/change_list.html" %}

{% block content %}
    <div>
        <h1>User Change View</h1>
        
        <!-- Display user information -->
        <h2>{{ original.name }}</h2>
        <p><strong>User ID:</strong> {{ original.user_id }}</p>
        <p><strong>Email:</strong> {{ original.email }}</p>

        <!-- Display the sync button only if it's present in the context -->
        {% if sync_button %}
            <form action="{% url 'admin:accounts_comanageuser_sync' user_id=original.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="button">Sync User from Comanage</button>
            </form>
        {% endif %}
    </div>

    {{ block.super }}
{% endblock %}

rcamp/accounts/templates/comanage_sync_detail.html
{% extends "admin/base.html" %}

{% block extrahead %}
    <link rel="stylesheet" type="text/css" href="/static/css/custom-admin.css">
{% endblock %}

{% block content %}
<h1>User Groups for {{ user_data.name }}</h1>

<p><strong>User ID:</strong> {{ user_data.user_id }}</p>
<p><strong>Email:</strong> {{ user_data.email }}</p>
<p><strong>Created At:</strong> {{ user_data.created_at }}</p>
<p><strong>Modified:</strong> {{ user_data.modified }}</p>

<h2>Groups</h2>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Group Name</th>
            <th>Created At</th>
            <th>Modified</th>
        </tr>
    </thead>
    <tbody>
        {% for group in groups %}
            <tr>
                <td>{{ group.Name }}</td>
                <td>{{ group.Created }}</td>
                <td>{{ group.Modified }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

rcamp/accounts/templates/comanage_sync_form.html
<!-- templates/admin/comanage_sync_form.html -->
{% extends "admin/base_site.html" %}

{% block content %}
  <h1>Sync Comanage User</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sync User</button>
  </form>
{% endblock %}

rcamp/accounts/templates/comanage_sync_list.html
{% extends 'admin/change_list.html' %}

{% block extrahead %}
    <link rel="stylesheet" type="text/css" href="/static/css/custom-admin.css">
{% endblock %}

{% block content %}

<div>
    <a href="{% url 'admin:comanage-sync-users' %}" class="button">Sync Users from Comanage</a>
</div>

{% block search %}
    <form method="get" class="search-form">
        <div class="form-group">
            <label for="search">Search</label>
            <input type="text" name="q" value="{{ request.GET.q }}" class="form-control" placeholder="Search by Email or User ID">
        </div>
        <button type="submit" class="btn btn-primary">Search</button>
    </form>
{% endblock %}

<table class="table table-bordered">
    <thead>
        <tr>
            <th>User ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>Created At</th>
            <th>Modified</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for user in user_data %}
        <tr>
            <td>{{ user.user_id }}</td>
            <td>{{ user.name }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.created_at }}</td>
            <td>{{ user.modified }}</td>
            <td>
                <a href="{% url 'admin:comanage-sync-user-detail' user_id=user.user_id %}">View Groups</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}