rcamp/projects/urls.py
from django.urls import include, re_path
from django.contrib.auth.decorators import login_required
from projects.views import ProjectListView
from projects.views import ProjectDetailView
from projects.views import ProjectEditView
from projects.views import ProjectCreateView
from projects.views import ReferenceDetailView
from projects.views import ReferenceEditView
from projects.views import ReferenceCreateView
from projects.views import AllocationRequestDetailView
from projects.views import AllocationRequestCreateView

urlpatterns = [
    re_path(r'^list$', login_required(ProjectListView.as_view()), name='project-list'),
    re_path(r'^list/(?P<pk>[-\w]+)/$', login_required(ProjectDetailView.as_view()), name='project-detail'),
    re_path(r'^list/(?P<pk>[-\w]+)/edit$', login_required(ProjectEditView.as_view()), name='project-edit'),
    re_path(r'^create$', login_required(ProjectCreateView.as_view()), name='project-create'),
    re_path(r'^list/(?P<project_pk>[-\w]+)/references/(?P<pk>[-\w]+)/$', login_required(ReferenceDetailView.as_view()), name='reference-detail'),
    re_path(r'^list/(?P<project_pk>[-\w]+)/references/(?P<pk>[-\w]+)/edit$', login_required(ReferenceEditView.as_view()), name='reference-edit'),
    re_path(r'^list/(?P<project_pk>[-\w]+)/references/create$', login_required(ReferenceCreateView.as_view()), name='reference-create'),
    re_path(r'^list/(?P<project_pk>[-\w]+)/allocationrequests/(?P<pk>[-\w]+)/$', login_required(AllocationRequestDetailView.as_view()), name='allocation-request-detail'),
    re_path(r'^list/(?P<project_pk>[-\w]+)/allocationrequests/create$', login_required(AllocationRequestCreateView.as_view()), name='allocation-request-create'),
]

rcamp/rcamp/urls.py
from django.urls import include, re_path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.conf.urls import handler404
from django.conf.urls import handler500
from django.conf import settings
# Make sure signals/receivers get loaded.
from mailer import receivers
from projects import receivers
from lib.views import index_view



handler404 = 'lib.views.handler404'
handler500 = 'lib.views.handler500'

urlpatterns = [
    re_path(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    re_path(r'^$', index_view, name='index'),
    re_path(r'^login', auth_views.LoginView.as_view(template_name='registration/login.html')),
    re_path(r'^logout', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^api/', include('endpoints.urls')),
    re_path(r'^accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    re_path(r'^projects/', include(('projects.urls', 'projects'), namespace='projects')),
]


if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += staticfiles_urlpatterns()

rcamp/projects/models.py
from dateutil.relativedelta import relativedelta
from django.db import models
from django.db.models import Func, F
from django.db.models.functions import Substr, Lower
from django.utils import timezone
from lib import fields

from accounts.models import User
from mailer.signals import allocation_created_from_request

class Cast(Func):
    function = 'CAST'
    template = '%(function)s(%(expressions)s as %(target_type)s)'

class Project(models.Model):
    ORGANIZATIONS = (
        ('ucb','University of Colorado Boulder'),
        ('csu','Colorado State University'),
        ('xsede','XSEDE'),
        ('amc', 'AMC'),
    )

    pi_emails = fields.ListField()
    managers = models.ManyToManyField(User,related_name='manager_on')
    collaborators = models.ManyToManyField(User,related_name='collaborator_on')
    organization = models.CharField(max_length=128,choices=ORGANIZATIONS)
    title = models.CharField(max_length=256)
    description = models.TextField()

    project_id = models.CharField(max_length=24,unique=True,blank=True,null=True)
    created_on = models.DateField(auto_now_add=True)
    notes = models.TextField(blank=True,null=True)

    parent_account = models.CharField(max_length=24,null=True,blank=True)
    qos_addenda = models.CharField(max_length=128,null=True,blank=True)
    deactivated = models.BooleanField(default=False)

    def __str__(self):
        return self.project_id

    def save(self,*args,**kwargs):
        if (not self.project_id) or (self.project_id == ''):
            # Assign new id to project.
            org = self.organization
            prefix_offset = len(org) + 1

            projects = Project.objects.filter(
                project_id__startswith=org
            ).annotate(
                project_number_int=Cast(Substr('project_id', prefix_offset), target_type='UNSIGNED')
            ).order_by('-project_number_int')

            if projects.count() == 0:
                next_id = '{}{}'.format(org.lower(),'1')
            else:
                last_id = projects[0].project_id
                last_id = last_id.replace(org,'')
                next_id = int(last_id) + 1
                next_id = '{}{}'.format(org.lower(),str(next_id))
            self.project_id = next_id
        super(Project,self).save(*args,**kwargs)

class Reference(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    description = models.TextField()
    link = models.TextField()
    created_on = models.DateField(auto_now_add=True)

    def __str__(self):
        return '{}_{}'.format((self.project.project_id,str(self.created_on)))

class AllocationManager(models.Manager):
    def create_allocation_from_request(self,**kwargs):
        project = kwargs.get('project')
        amount_awarded = kwargs.get('amount_awarded', None)

        if not project:
            raise TypeError('Missing required field: project')

        if amount_awarded == None:
            raise TypeError('Missing required field: amount_awarded')

        now = timezone.now()
        next_year = now + relativedelta(years=1)

        alloc_fields = {}
        alloc_fields['project'] = project
        alloc_fields['amount'] = amount_awarded
        alloc_fields['start_date'] = now
        alloc_fields['end_date'] = next_year

        alloc = self.create(**alloc_fields)
        return alloc

class Allocation(models.Model):
    objects = AllocationManager()

    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    allocation_id = models.SlugField(unique=True,blank=True,null=True)
    amount = models.BigIntegerField()
    created_on = models.DateField(auto_now_add=True)
    start_date = models.DateField()
    end_date = models.DateField()
    expiration_notice_sent = models.BooleanField(default=False)

    def __str__(self):
        return self.allocation_id

    def save(self,*args,**kwargs):
        alloc_id_tpl = '{project_id}_summit{alloc_enum}'

        if (not self.allocation_id) or (self.allocation_id == ''):
            proj_id = self.project.project_id
            search_prefix = '{project_id}_summit'.format(project_id=proj_id)
            prefix_offset = len(proj_id) + 1
            allocs = Allocation.objects.filter(
                allocation_id__startswith=search_prefix
            ).annotate(
                alloc_number_int=Cast(Substr('allocation_id', prefix_offset), target_type='UNSIGNED')
            ).order_by('-alloc_number_int')

            if allocs.count() == 0:
                next_id = alloc_id_tpl.format(
                    project_id=proj_id.lower(),
                    alloc_enum='1'
                )
            else:
                last_id = allocs.order_by('-allocation_id')[0].allocation_id
                last_id = last_id.replace(proj_id+'_summit','')
                next_id = int(last_id) + 1
                next_id = alloc_id_tpl.format(
                    project_id=proj_id.lower(),
                    alloc_enum=str(next_id)
                )
            self.allocation_id = next_id
        super(Allocation,self).save(*args,**kwargs)

class AllocationRequest(models.Model):
    STATUSES = (
        ('a','Approved'),
        ('d','Denied'),
        ('w','Waiting'),
        ('h','Hold'),
        ('r','Ready For Review'),
        ('q','Response Requested'),
        ('i','Denied - Insufficient Resources'),
        ('x','Denied - Proposal Incomplete'),
        ('f','Approved - Fully Funded'),
        ('p','Approved - Partially Funded'),
    )

    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    allocation = models.ForeignKey(
            Allocation,
            null=True,
            blank=True,
            on_delete=models.CASCADE
            )

    abstract = models.TextField(null=True,blank=True)
    funding = models.TextField(null=True,blank=True)
    proposal = models.FileField(upload_to='proposals/%Y/%m/%d',null=True,blank=True)
    time_requested = models.BigIntegerField(null=True,blank=True)

    amount_awarded = models.BigIntegerField(default=0)
    disk_space = models.IntegerField(default=0,null=True,blank=True)
    software_request = models.TextField(null=True,blank=True)

    requester = models.ForeignKey(User,null=True,blank=True,on_delete=models.CASCADE)
    request_date = models.DateTimeField(auto_now_add=True)

    status = models.CharField(max_length=16,choices=STATUSES,default='w')
    approved_on = models.DateTimeField(null=True,blank=True)
    notes = models.TextField(null=True,blank=True)

    def __str__(self):
        return '{}_{}'.format(self.project.project_id,self.request_date)

    def save(self,*args,**kwargs):
        # Check for change in approval status
        if (self.status in ['a','f','p']) and (not self.approved_on):
            # Approval process
            # logger.info('Approving project request: '+self.__str__())
            alloc = Allocation.objects.create_allocation_from_request(
                project = self.project,
                amount_awarded = self.amount_awarded
            )
            self.amount_awarded = alloc.amount
            allocation_created_from_request.send(sender=alloc.__class__,allocation=alloc)
            self.approved_on=timezone.now()
            self.allocation = alloc

        super(AllocationRequest,self).save(*args,**kwargs)

rcamp/projects/forms.py
from django import forms
from django.contrib import admin

from lib.fields import MultiEmailField
from accounts.models import (
    RcLdapUser,
    User
)
from projects.models import Project


class ProjectMembersModelMultipleChoiceField(forms.ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return u'{} ({} {})'.format(obj.username,obj.first_name,obj.last_name)

class ProjectForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = [
            'title',
            'description',
            'pi_emails',
            'managers',
            'collaborators',
            'organization',
        ]

    pi_emails = MultiEmailField(required=True)
    managers = ProjectMembersModelMultipleChoiceField(
        queryset=User.objects.all().order_by('username'),
        required=False,
        widget=admin.widgets.FilteredSelectMultiple(
            'managers',
            False,
        )
    )
    collaborators = ProjectMembersModelMultipleChoiceField(
        queryset=User.objects.all().order_by('username'),
        required=False,
        widget=admin.widgets.FilteredSelectMultiple(
            'collaborators',
            False,
        )
    )

class ProjectEditForm(ProjectForm):
    class Meta:
        model = Project
        fields = [
            'title',
            'description',
            'pi_emails',
            'managers',
            'collaborators',
        ]

class ReferenceForm(forms.Form):
    description = forms.CharField(widget=forms.Textarea,required=True)
    link = forms.CharField(widget=forms.Textarea,required=True)

class AllocationRequestForm(forms.Form):
    VALID_DOC_TYPES = ['application/msword', 'application/pdf', 'text/plain','application/vnd.openxmlformats-officedocument.wordprocessingml.document']

    proposal = forms.FileField(required=True)

    def clean(self):
        cleaned_data = super(AllocationRequestForm,self).clean()
        proposal = cleaned_data.get('proposal')
        err_proposal = []
        if proposal:
            if proposal.size > (1024**2) * 10:
                err_proposal += ['File size over 10MB']
            if proposal.content_type not in self.VALID_DOC_TYPES:
                err_proposal += ['Invalid file type. Must be a PDF, DOC, DOCX, or TXT.']
            if len(err_proposal) > 0:
                self._errors['proposal'] = self.error_class(err_proposal)

        return cleaned_data

class StartupRequestForm(forms.Form):
    reason = forms.CharField(widget=forms.Textarea,required=True)
    disk_space = forms.IntegerField(min_value=0,required=False)
    software_request = forms.CharField(widget=forms.Textarea,required=False)

rcamp/projects/templates/allocation-request-create.html
{% extends "base.html" %}

{% block title %}Research Computing - Request Allocation{% endblock %}

{% block extra_style %}
<link href="/static/css/projects.css" type="text/css" media="all" rel="stylesheet">
{% endblock %}

{% block container %}
<div class="row">
  <div class="jumbotron text-center">
    <h1>Request an allocation</h1>
    <p>Request a compute time allocation for {{ project.project_id }}</p>
  </div>
</div>

<div class="row">
  <ol class="breadcrumb">
    <li><a href="{% url 'index' %}">Index</a></li>
    <li><a href="{% url 'projects:project-list' %}">My Projects</a></li>
    <li><a href="{% url 'projects:project-detail' pk=project.pk %}">{{ project.project_id}}</a></li>
    <li class="active">Request Allocation</li>
  </ol>

  {% if form.errors %}
  <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <p>
      <strong>Could not create request.</strong>
      Please resolve the errors below, or
      <a href="mailto:rc-help@colorado.edu?subject=Question%20About%20Allocation%20Request">
        Contact us
      </a>
    </p>
    {{ form.non_field_errors }}
  </div>
  {% endif %}

  <form class="form-horizontal" method="POST" action="" role="form" enctype="multipart/form-data">
    {% csrf_token %}

    <fieldset>
      <legend>Submit Your Proposal</legend>

      <div class="alert alert-info" role="alert">
        You should create your allocation request Proposal Document from the template and instructions provided in our <a href="https://www.colorado.edu/rc/userservices/allocations">Allocation Request Documentation <span class="glyphicon glyphicon-new-window"></span></a>. Upload your completed proposal document below. <strong>Proposals that do not follow the template will not be accepted.</strong>
      </div>

      {% if form.proposal.errors %}
      <div class="form-group has-error has-feedback">
      {% else %}
      <div class="form-group">
      {% endif %}
        <label class="col-md-2 control-label" for="id_proposal">Proposal document <small>(max. 10MB)</small></label>
        <div class="col-md-10">
          {{ form.proposal }}
          {% if form.proposal.errors %}
          <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>{{ form.proposal.errors }}</strong>
          </div>
          {% endif %}
        </div>
      </div>
    </fieldset>

    <div class="request-submit text-center">
        <button type="submit" class="btn btn-primary btn-lg">Submit Request</button>
    </div>

  </form>
</div>
{% endblock %}

rcamp/projects/templates/project-create.html
{% extends "base.html" %}

{% block title %}Research Computing - Create Project{% endblock %}

{% block extra_style %}
<link href="/static/css/projects.css" type="text/css" media="all" rel="stylesheet">
<link href="/static/css/selector.css" rel="stylesheet"/>
{% endblock %}

{% block container %}
<div class="row">
  <div class="jumbotron text-center">
    <h1>Create a new project</h1>
    <p>Create a new Research Computing project.</p>
  </div>
</div>

<ol class="breadcrumb">
  <li><a href="{% url 'index' %}">Index</a></li>
  <li><a href="{% url 'projects:project-list' %}">My Projects</a></li>
  <li class="active">Create Project</li>
</ol>

{% if form.errors %}
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <p>
    <strong>Could not create project.</strong>
    Please resolve the errors below, or
    <a href="mailto:rc-help@colorado.edu?subject=Question%20About%20Project%20Creation">
      Contact us
    </a>
  </p>
  {{ form.non_field_errors }}
</div>
{% endif %}

<form class="form-horizontal" method="POST" action="" role="form" enctype="multipart/form-data">
  {% csrf_token %}

  <fieldset>
    <legend>Select the sponsoring organization</legend>
    <div class="mailto-help">
      <small>
        Questions about project creation?
        <a href="mailto:rc-help@colorado.edu?subject=Question%20About%20Project%20Creation">
          Contact us
        </a>
        or view our
          <a href="https://www.colorado.edu/rc/userservices/allocations">
            allocations documentation.
          </a>
      </small>
    </div>
    {% if form.organization.errors %}
    <div class="form-group has-error has-feedback">
    {% else %}
    <div class="form-group">
    {% endif %}
      <label class="col-sm-2 control-label" for="id_organization">Organization</label>
      <div class="col-sm-8">
        <select name="organization" id="id_organization" class="form-control">
          {% for value, disp in form.organization.field.choices %}
          <option value="{{ value }}">{{ disp }}</option>
          {% endfor %}
        </select>
        {% if form.organization.errors %}
        <div class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <strong>{{ form.organization.errors }}</strong>
        </div>
        {% endif %}
      </div>
    </div>
  </fieldset>

  <fieldset>
    <legend>Describe your project</legend>
    {% if form.title.errors %}
    <div class="form-group has-error has-feedback">
    {% else %}
    <div class="form-group">
    {% endif %}
        <label class="col-sm-2 control-label" for="id_title">Title</label>
        <div class="col-sm-8">
            <input id="id_title" type="text" name="title" class="form-control"
            {% if form.title.value %}value="{{ form.title.value }}"{% endif %}
            maxlength="256" />
            {% if form.title.errors %}
            <div class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <strong>{{ form.title.errors }}</strong>
            </div>
            {% endif %}
        </div>
    </div>

    {% if form.description.errors %}
    <div class="form-group has-error has-feedback">
    {% else %}
    <div class="form-group">
    {% endif %}
        <label class="col-sm-2 control-label" for="id_description">Description</label>
        <div class="col-sm-8">
          <textarea id="id_description" name="description" class="form-control" rows="10" cols="40" placeholder="A concise description this project's purpose. 100 words or fewer." />{% if form.description.value %}{{ form.description.value }}{% endif %}</textarea>
          {% if form.description.errors %}
          <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>{{ form.description.errors }}</strong>
          </div>
          {% endif %}
        </div>
    </div>
  </fieldset>

  <fieldset>
    <legend>Primary Investigators</legend>
    {% if form.pi_emails.errors %}
    <div class="form-group has-error has-feedback">
    {% else %}
    <div class="form-group">
    {% endif %}
        <label class="col-sm-2 control-label" for="id_pi_emails">PI Emails (comma-separated)</label>
        <div class="col-sm-8">
            <input id="id_pi_emails" type="text" name="pi_emails" class="form-control"
            {% if form.pi_emails.value %}value="{{ form.pi_emails.value }}"{% endif %}
            maxlength="256" />
            {% if form.pi_emails.errors %}
            <div class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <strong>{{ form.pi_emails.errors }}</strong>
            </div>
            {% endif %}
        </div>
    </div>
  </fieldset>

  <fieldset>
    <legend>Project Managers</legend>
    <div class="mailto-help">
      <small>
        These accounts will be authorized to make changes to the project and to submit allocation requests and should include the research group PI.
      </small>
    </div>
    {{ form.managers }}
    {% if form.managers.errors %}
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <strong>{{ form.managers.errors }}</strong>
    </div>
    {% endif %}
  </fieldset>

  <fieldset>
    <legend>Project Collaborators</legend>
    <div class="mailto-help">
      <small>
        These accounts will be able to run compute jobs in this project's allocations.
      </small>
    </div>
    {{ form.collaborators }}
    {% if form.collaborators.errors %}
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <strong>{{ form.collaborators.errors }}</strong>
    </div>
    {% endif %}
  </fieldset>

  <div class="col-sm-2 col-sm-offset-5 request-submit">
      <button type="submit" class="btn btn-primary btn-lg">Create Project</button>
  </div>
</form>
{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/js/jsi18n.js"></script>
<script type="text/javascript" src="/static/js/SelectBox.js"></script>
<script type="text/javascript" src="/static/js/SelectFilter2.js"></script>
{% endblock %}

rcamp/projects/templates/project-detail.html
{% extends "base.html" %}

{% block title %}Research Computing - My Projects{% endblock %}

{% block extra_style %}
<link href="/static/css/projects.css" rel="stylesheet"/>
{% endblock %}

{% block container %}
<div class="row">

  <ol class="breadcrumb">
    <li><a href="{% url 'index' %}">Index</a></li>
    <li><a href="{% url 'projects:project-list' %}">My Projects</a></li>
    <li class="active">{{ object.project_id }}</li>
  </ol>

  {% if edit_warning %}
  <div class="alert alert-danger" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <p><strong>No edit permissions for {{ object.project_id }}!</strong> You must be a project manager to edit.</p>
  </div>
  {% endif %}

  <legend>Project: {{ object.project_id }}
    {% if user in object.managers.all %}<a href="{% url 'projects:project-edit' object.pk %}" class="project-edit-link">(edit project)</a>{% endif %}
  </legend>
  <div class="mailto-help">
      <small>
        Questions about this project or its allocations?
        <a href="mailto:rc-help@colorado.edu?subject=Question%20About%20Project%20(%23{{object.project_id}})">
            Contact us.
        </a>
      </small>
  </div>
  <div class="table-responsive">
    <table class="table table-striped">
      <tr id="table-id-row">
        <td><strong>Project ID</strong></td>
        <td>{{ object.project_id }}</td>
      </tr>
      <tr id="table-organization-row">
        <td><strong>Organization</strong></td>
        <td>{{ object.organization | upper }}</td>
      </tr>
      <tr id="table-title-row">
        <td><strong>Title</strong></td>
        <td>{{ object.title }}</td>
      </tr>
      <tr id="table-description-row">
        <td><strong>Description</strong></td>
        <td>{{ object.description }}</td>
      </tr>
      <tr id="table-pi_emails-row">
        <td><strong>PI Emails</strong></td>
        <td>{% for pi_email in object.pi_emails %}
          {{ pi_email }}{% if not forloop.last %},&nbsp;{% endif %}
        {% endfor %}</td>
      </tr>
      <tr id="table-manager_list-row">
        <td><strong>Project Managers</strong></td>
        <td>{% for manager in object.managers.all %}
          {{ manager.first_name }} {{ manager.last_name }} ({{ manager.username }}){% if not forloop.last %},&nbsp;{% endif %}
        {% endfor %}</td>
      </tr>
      <tr id="table-collaborator_list-row">
        <td><strong>Project Collaborators</strong></td>
        <td>{% for collaborator in object.collaborators.all %}
          {{ collaborator.first_name }} {{ collaborator.last_name }} ({{ collaborator.username }}){% if not forloop.last %},&nbsp;{% endif %}
        {% endfor %}</td>
      </tr>
      <tr id="table-created_on-row">
        <td><strong>Created On</strong></td>
        <td>{{ object.created_on }}</td>
      </tr>
    </table>
  </div>

  {% if user in object.managers.all %}
  <legend>References and publications for {{ object.project_id }}</legend>

  <div class="mailto-help">
    <small>
      RC resources must be acknowledged in any published or presented work for which results were obtained using them. Take a look at our <a href="https://www.colorado.edu/rc/resources/citations">citation instructions.</a>
    </small>
  </div>


  <ul class="list-group">
    {% for reference in references %}
    <a href="{% url 'projects:reference-detail' project_pk=object.pk pk=reference.pk %}" class="list-group-item">
      <h4 class="list-group-item-heading">{{ reference.description }}</h4>
      <p class="list-group-item-text">
        {{ reference.link }}
      </p>
    </a>
    {% endfor %}
    <a href="{% url 'projects:reference-create' project_pk=object.pk %}" id="reference-add-link" class="list-group-item">
      <h4 class="list-group-item-heading">Add reference</h4>
      <p class="list-group-item-text">
        Define a new publication or reference for this project.
      </p>
    </a>
  </ul>
  {% endif %}

  {% if user in object.managers.all %}
  <legend>Allocations and Requests for {{ object.project_id }}</legend>

  <div class="mailto-help">
    <small>
      When you receive an account you will automatically be assigned a general share for your organization, which is a great place to run smaller jobs or to use to test and benchmark your code. General share users have a lower priority. To receive higher priority, you can apply for an allocation to run on our systems. Questions about projects and allocations?
      <a href="mailto:rc-help@colorado.edu?subject=Question%20About%20Project%20Creation">
        Contact us
      </a>
      or view our
        <a href="https://www.colorado.edu/rc/userservices/allocations">
          allocations documentation.
        </a>
    </small>
  </div>

  <ul class="list-group">
    {% for allocation_request in allocation_requests %}
    <a href="{% url 'projects:allocation-request-detail' project_pk=object.pk pk=allocation_request.pk %}" class="list-group-item">
      <h4 class="list-group-item-heading">{{ allocation_request.request_date }}</h4>
      <p class="list-group-item-text">
        {% for status in allocation_request.STATUSES %}
        {% if allocation_request.status == status.0 %}
        <strong>Status:</strong> {{ status.1 }}
        {% endif %}
        {% endfor %}
      </p>
      {% if allocation_request.status == 'a' %}
      <p class="list-group-item-text">
        <strong>Allocation ID:</strong> {{ allocation_request.allocation.allocation_id }}
      </p>
      <p class="list-group-item-text">
        <strong>Allocated Time:</strong> {{ allocation_request.allocation.amount }}
      </p>
      {% endif %}
    </a>
    {% endfor %}
    <a href="{% url 'projects:allocation-request-create' project_pk=object.pk %}" id="allocation-request-link" class="list-group-item">
      <h4 class="list-group-item-heading">Request an allocation</h4>
      <p class="list-group-item-text">
        Request a compute time allocation for this project.
      </p>
    </a>
  </ul>
  {% else %}
  <legend>Allocations for {{ object.project_id }}</legend>
  <ul class="list-group">
    {% for allocation in allocations %}
    <h4 class="list-group-item-heading">{{ allocation.allocation_id }}</h4>
    <p class="list-group-item-text">
      <strong>Allocated Time:</strong> {{ allocation.amount }} SU
    </p>
    {% endfor %}
  </ul>
  {% endif %}
</div>
{% endblock %}