rcamp/accounts/urls.py
from django.urls import include, path, re_path
from . import admin
from accounts.views import (
    AccountRequestOrgSelectView,
    AccountRequestVerifyUcbView,
    AccountRequestVerifyCsuView,
    AccountRequestIntentView,
    AccountRequestReviewView,
)


urlpatterns = [
    re_path(
        r'^account-request/create/organization$',
        AccountRequestOrgSelectView.as_view(),
        name='account-request-org-select'
    ),
    re_path(
        r'^account-request/create/verify/ucb$',
        AccountRequestVerifyUcbView.as_view(),
        name='account-request-verify-ucb'
    ),
    re_path(
        r'^account-request/create/verify/csu$',
        AccountRequestVerifyCsuView.as_view(),
        name='account-request-verify-csu'
    ),
    re_path(
        r'^account-request/create/intent$',
        AccountRequestIntentView.as_view(),
        name='account-request-intent'
    ),
    re_path(
        r'^account-request/review$',
        AccountRequestReviewView.as_view(),
        name='account-request-review'
    ),
]

# removed path('admin/accounts/comanageuser/<int:user_id>/sync/', sync_user_from_comanage, name='accounts_comanageuser_sync'),

rcamp/rcamp/urls.py
from django.urls import include, re_path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.conf.urls import handler404
from django.conf.urls import handler500
from django.conf import settings
# Make sure signals/receivers get loaded.
from mailer import receivers
from projects import receivers
from lib.views import index_view



handler404 = 'lib.views.handler404'
handler500 = 'lib.views.handler500'

urlpatterns = [
    re_path(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    re_path(r'^$', index_view, name='index'),
    re_path(r'^login', auth_views.LoginView.as_view(template_name='registration/login.html')),
    re_path(r'^logout', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^api/', include('endpoints.urls')),
    re_path(r'^accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    re_path(r'^projects/', include(('projects.urls', 'projects'), namespace='projects')),
]


if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += staticfiles_urlpatterns()

rcamp/rcamp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
{% block head %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="https://www.colorado.edu/rc/profiles/express/themes/cusimple/favicon.ico" type="image/vnd.microsoft.icon">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link href="/static/css/rcamp.css" rel="stylesheet" />

	{% block extra_style %}{% endblock %}

    <title>{% block title %}Research Computing{% endblock %}</title>

{% endblock %}
</head>

<body>
{% block body %}
<div class="container">

    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="{% url 'index' %}"><img class="navbar-logo" src="/static/img/logo.png"/></a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    {% if request.user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user" aria-hidden="true"></i>&nbsp;{{ request.user.username }}<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="/projects/list">Manage My Projects</a></li>
                            {% if request.user.is_authenticated %}
                            <li><a href="/admin">Admin</a></li>
                            {% endif %}
                            <li>
                                <form method="post" action="{% url 'logout' %}" style="display:inline;">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-link p-0 align-baseline">Log out</button>
                                </form>
                            </li>
                        </ul>
                    </li>
                    {% else %}
                    <li><a href="/login">Login</a></li>
                    {% endif %}
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>

    {% block modal %}
    <!-- Modal -->
    <div class="modal fade" id="helpmodal" tabindex="-1" role="dialog" aria-labelledby="helpmodallabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    {% block modal_title %}
                    <h4 class="modal-title">Definitions &amp; Form Help</h4>
                    {% endblock %}
                </div>
                <div class="modal-body">
                    {% block modal_body %}{% endblock %}
                </div>
                <div class="modal-footer">
                {% block modal_footer %}{% endblock %}
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    {% endblock %}

    <div class="container body-content">
    {% block container %}

    {% endblock %}
    </div>
</div>
{% endblock %}

{% block footer %}
<div id="footer">
    <div class="container">
        {% block footer_content %}<br /><br />{% endblock %}
    </div>
</div>
{% endblock %}

{% block js %}
  <script src="//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
{% endblock %}

{% block extra_js %}{% endblock %}
</body>
</html>

rcamp/rcamp/templates/index.html
{% extends "base.html" %}

{% block container %}
<div class="row">
    <div class="jumbotron text-center">
        <h1>Research Computing</h1>
        <p>Welcome to Research Computing!</p>
    </div>
</div>

<div class="row">

    <div class="col-md-4 col-md-offset-1 text-center">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Account Request</h3>
            </div>
            <div class="panel-body">
                <p>Request a Research Computing account to access our resources and manage projects.</p>
                <a href="{% url 'accounts:account-request-org-select' %}">
                    <button type="submit" class="btn btn-primary btn-block">Request Account &raquo;</button>
                </a>
            </div>
        </div>
    </div>

    <div class="col-md-4 col-md-offset-1 text-center">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Sign In</h3>
            </div>
            <div class="panel-body">
                <p>Sign in to request compute access or manage your projects and allocation requests.</p>
                <a href="/login">
                    <button type="submit" class="btn btn-primary btn-block">Sign In &raquo;</button>
                </a>
            </div>
        </div>
    </div>

</div>
{% endblock %}